export const ADD_TODO = "ADD_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
export const TOGGLE_UPDATE_TODO = "BE_UPDATE_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const CHANGING_STATE_TODO = "CHANGING_STATE_TODO";
